### ISSUE TITLE
Improve warning "No namespace detected" for files with hidden packages

### ISSUE THREAD

**Issue by dolmen** [kentnl/Dist-Zilla-Plugin-MetaProvides-Package#3]
When ones want to hide a package from indexing using the `package \n Foo;` trick, those files are reported as "No namespace detected". This is correct, but the impression the message gives is that is an error that has to be fixed while this is in fact exactly what the author wants. This is somewhat a kind of false positive that may be confusing for other contributors to that project.

It would be more useful to report that the file has namespaces, but that they are explicitely hidden, and may be report this only while in verbose/debug mode.

See also dagolden/Dist-Zilla-Plugin-BumpVersionAfterRelease#7 that is somewhat related.

**Comment by kentfredric** [comment]
This is slightly challenging to do, for the layer I'm at, I'm simply using `Module::Metadata` to determine namespace existence and not.

`Module::Metadata` is what is responding to the `package \n Foo` trick, and so that conclusion is squirrelled away from me prior to it being something I can check for.

I'd gladly fix this if there's a viable workaround though, I'd just need to know how to do so reliably.

**Comment by kentfredric** [comment]
https://rt.cpan.org/Ticket/Display.html?id=101439

**Comment by dolmen** [comment]
Fixed in e6ee0caf2efe49566bb999b55be92f07b05de8b2
